import { readFileSync, writeFileSync } from "node:fs";
import type { StyleDef } from "./contract.ts";
import { substituteStyle, toneColors } from "./contract.ts";
import { join } from "node:path";
import type { SceneBuild } from "./scenes.ts";
import type { SoundPlan } from "./sound.ts";
import type { VideoSpec } from "./spec.ts";
import type { BeatTiming } from "./timeline.ts";
import { warpAt } from "./timeline.ts";
import type { VoiceLine } from "./voice.ts";
import type { BeatWords } from "./words.ts";
import { ENGINE_DIR, VENDOR_SKILLS, copyInto, ensureDir, fail, log, r3, run, stripAnsi, writeJson } from "./lib/util.ts";

export interface AssembleInput {
  spec: VideoSpec;
  style: StyleDef;
  buildDir: string;
  voices: VoiceLine[];
  words: BeatWords[];
  timings: BeatTiming[];
  sound: SoundPlan;
  scenes: SceneBuild[];
}

// Voice chain rides on every narration clip, never on a bus: a bus with data-fx-chain fails on the
// engine's float WAV (TRAPS.md, «FX на аудиошине»).
const VOICE_CHAIN = {
  version: 1,
  nodes: [
    { type: "highpass", id: "n1", label: "Remove Rumble", params: { frequency: 70, q: 0.707, poles: "2" } },
    { type: "peaking", id: "n2", label: "Reduce Mud", params: { frequency: 250, gain: -2, q: 1.2 } },
    { type: "peaking", id: "n4", label: "Add Clarity", params: { frequency: 3000, gain: 1.5, q: 1 } },
    { type: "limiter", id: "n5", label: "Peak Ceiling", params: { limit: -2.5, attack: 5, release: 60, level_out: 0 } },
  ],
};

const attr = (o: unknown): string => JSON.stringify(o).replace(/&/g, "&amp;").replace(/"/g, "&quot;");

function nodeScript(script: string, args: string[], cwd: string, keep = 8): void {
  const r = run(process.execPath, [script, ...args], { cwd });
  const lines = stripAnsi(r.stdout + r.stderr).trim().split("\n").filter((l) => l.trim());
  for (const line of lines.slice(0, keep)) log.info(line.trim());
}

/**
 * HyperFrames project in build/: captions.mjs → assemble-index.mjs (vendored skill scripts) →
 * finishing pass (buses, drone, SFX, shader transition, grain, vignette, local scripts) → carve.
 */
export function assembleProject(input: AssembleInput): number {
  const { spec, style, buildDir } = input;
  stage(spec, style, buildDir);
  writeStoryboard(input);
  writeAudioMeta(input);
  const scripts = join(VENDOR_SKILLS, "faceless-explainer", "scripts");
  nodeScript(join(scripts, "captions.mjs"), ["build", "--storyboard", "STORYBOARD.md", "--audio-meta", "audio_meta.json", "--hyperframes", ".", "--out", "caption_groups.json"], buildDir, 3);
  nodeScript(join(scripts, "assemble-index.mjs"), ["--storyboard", "STORYBOARD.md", "--hyperframes", "."], buildDir, 12);
  const total = finalizeIndex(input, style);
  carveBeds(input);
  writeVerifyPlan(input, style, total);
  return total;
}

function stage(spec: VideoSpec, style: StyleDef, buildDir: string): void {
  copyInto(join(ENGINE_DIR, "assets", "fonts"), join(buildDir, "assets", "fonts"));
  copyInto(join(ENGINE_DIR, "assets", "vendor"), join(buildDir, "assets", "vendor"));
  copyInto(join(ENGINE_DIR, "styles", spec.style, "frame.md"), join(buildDir, "frame.md"));
  const skin = readFileSync(join(ENGINE_DIR, "captions", `${spec.captions}.html`), "utf8");
  ensureDir(join(buildDir, ".hyperframes"));
  writeFileSync(join(buildDir, ".hyperframes", "caption-skin.html"), substituteStyle(skin, style, "accent", `engine/captions/${spec.captions}.html`));
  writeJson(join(buildDir, "hyperframes.json"), {
    $schema: "https://hyperframes.heygen.com/schema/hyperframes.json",
    paths: { blocks: "compositions", components: "compositions/components", assets: "assets" },
    media: { autoProxy: true },
  });
  writeJson(join(buildDir, "meta.json"), { id: spec.id, name: spec.id });
}

function writeStoryboard({ spec, buildDir, timings, voices }: AssembleInput): void {
  const total = (timings[timings.length - 1] as BeatTiming).end;
  const lines = [
    "---",
    `format: ${spec.format}`,
    `duration: ${total}s`,
    `message: ${JSON.stringify(spec.title)}`,
    "arc: story-explainer",
    "mode: autonomous",
    "---",
    "",
    `# STORYBOARD — ${spec.id}`,
    "",
    "> Generated by the hygen engine from video.json on every build. Do not edit.",
    "",
  ];
  spec.beats.forEach((beat, i) => {
    const t = timings[i] as BeatTiming;
    lines.push(
      `## Frame ${i + 1} — ${beat.id}`,
      `- duration: ${t.duration}s`,
      "- status: animated",
      `- src: compositions/frames/${beat.id}.html`,
      `- transition_in: ${spec.transitions.find((tr) => tr.to === beat.id && tr.type === "shader")?.shader ?? "cut"}`,
      `- voiceover: ${JSON.stringify((voices[i] as VoiceLine).tts)}`,
      "",
    );
  });
  writeFileSync(join(buildDir, "STORYBOARD.md"), lines.join("\n"));
}

function writeAudioMeta({ buildDir, voices, words, sound }: AssembleInput): void {
  writeJson(join(buildDir, "audio_meta.json"), {
    bgm: null,
    bgm_pending: false,
    voices: voices.map((v, i) => ({ frame: i + 1, path: v.rel, duration_s: v.duration, words: (words[i] as BeatWords).tokens })),
    sfx: sound.sfx.map((c) => ({ frame: c.frame, file: c.file, offset_s: c.offset_s, duration_s: c.duration_s, volume: c.volume })),
  });
}

/** Finishing pass over assemble-index's output — ported from examples/pompeii-short/scripts/assemble/finalize_index.mjs. */
function finalizeIndex({ spec, buildDir, timings, sound }: AssembleInput, style: StyleDef): number {
  const colors = toneColors(style, "accent");
  const rgb = (name: string): string => [1, 3, 5].map((i) => parseInt((colors[name] as string).slice(i, i + 2), 16)).join(", ");
  const indexPath = join(buildDir, "index.html");
  let html = readFileSync(indexPath, "utf8");

  const hosts: { id: string; block: string }[] = [];
  for (const m of html.matchAll(/<div\s+id="el-([^"]+)"\s+class="scene"([^>]*)><\/div>/g)) {
    if (/data-composition-src="compositions\/frames\//.test(m[2] as string)) hosts.push({ id: m[1] as string, block: m[0] });
  }
  if (hosts.length !== timings.length) fail(`index.html: ожидалось ${timings.length} сцен, найдено ${hosts.length}`);
  const total = Number(/data-composition-id="main"[^>]*?data-duration="([\d.]+)"/s.exec(html)?.[1]);
  if (!Number.isFinite(total)) fail("index.html: нет data-duration у корня");

  // 1. hosts: the outgoing scene of a shader transition is held under the blend; solid grounds for the shader pair
  const shaderTr = spec.transitions.filter((tr) => tr.type === "shader");
  const flashTr = spec.transitions.filter((tr) => tr.type === "flash");
  const held = new Map<string, number>();
  for (const tr of shaderTr) {
    const from = timings.find((t) => t.id === tr.from) as BeatTiming;
    held.set(tr.from, r3(from.duration + tr.duration));
  }
  const shaderIds = new Set(shaderTr.flatMap((tr) => [tr.from, tr.to]));
  hosts.forEach((h, i) => {
    let block = h.block.replace(/\sstyle="[^"]*"/, "").replace(/data-track-index="\d+"/, `data-track-index="${i % 2}"`);
    const heldDur = held.get(h.id);
    if (heldDur) block = block.replace(/data-duration="[\d.]+"/, `data-duration="${heldDur}"`);
    if (shaderIds.has(h.id)) block = block.replace(/class="scene"/, `class="scene" style="background-color: ${colors.ground}"`);
    html = html.replace(h.block, block);
  });
  for (const [id, heldDur] of held) {
    const base = (timings.find((t) => t.id === id) as BeatTiming).duration;
    const framePath = join(buildDir, "compositions", "frames", `${id}.html`);
    let rootDone = false;
    const out = readFileSync(framePath, "utf8").replace(/<([A-Za-z][\w:-]*)\b([^>]*)>/g, (tag: string, name: string, attrs: string) => {
      const dm = /\bdata-duration="([\d.]+)"/.exec(attrs);
      if (!rootDone && attrs.includes(`data-composition-id="${id}"`)) {
        rootDone = true;
        return dm ? tag.replace(/\bdata-duration="[\d.]+"/, `data-duration="${heldDur}"`) : tag.replace(/(\s*\/?>)$/, ` data-duration="${heldDur}"$1`);
      }
      if (!dm || name.toLowerCase() === "audio") return tag;
      const sm = /\bdata-start="([\d.]+)"/.exec(attrs);
      if (!sm) return tag;
      const start = Number(sm[1]);
      if (start + Number(dm[1]) < base - 0.011) return tag;
      return tag.replace(/\bdata-duration="[\d.]+"/, `data-duration="${r3(heldDur - start)}"`);
    });
    if (!rootDone) fail(`${framePath}: нет корня data-composition-id="${id}"`);
    writeFileSync(framePath, out);
  }

  // 2. head: GSAP and the shader runtime from the project, never a CDN; overlay styles
  html = html.replace(/<script src="https:\/\/cdn\.jsdelivr\.net\/npm\/gsap@[^"]+"[^>]*><\/script>/, () =>
    '<script src="assets/vendor/gsap.min.js"></script>' +
    (shaderTr.length ? '\n    <script src="assets/vendor/shader-transitions.global.js"></script>' : ""),
  );
  if (/https?:\/\/cdn\./.test(html)) fail("index.html: остались скрипты с CDN");
  const overlayCss = `
      /* global finish (engine/src/assemble.ts) */
      #el-captions { z-index: 35; }
      #hf-vignette { position: absolute; inset: 0; pointer-events: none; z-index: 30;
        background: radial-gradient(ellipse 78% 64% at 50% 42%, rgba(${rgb(style.vignette.color)}, 0) ${style.vignette.clear}%, rgba(${rgb(style.vignette.color)}, ${style.vignette.alpha}) 100%); }
      #grain-overlay { position: absolute; inset: 0; pointer-events: none; z-index: 40; overflow: hidden; }
      #grain-texture { position: absolute; top: -50%; left: -50%; width: 200%; height: 200%; }
      #grain-dark, #grain-light { position: absolute; inset: 0; background-size: 512px 512px; }
      #grain-dark { background-image: url("assets/grain/grain-dark.png"); opacity: ${style.grain.dark}; }
      #grain-light { background-image: url("assets/grain/grain-light.png"); opacity: ${style.grain.light}; }` +
    (flashTr.length
      ? `
      .hf-flash { position: absolute; inset: 0; pointer-events: none; z-index: 28; background-color: ${colors.text}; opacity: 0; }
      #hf-burst { position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; pointer-events: none; z-index: 29; }`
      : "");
  html = html.replace(/(\s*)<\/style>\s*<\/head>/, () => `${overlayCss}\n    </style>\n  </head>`);

  // 3. body: voices on the voiceover bus (lanes 10/12 — lint duplicate_audio_track), SFX ids + bus, rounding
  html = html.replace(/<audio\s+id="el-([^"]+)-voice"(?![^>]*data-audio-group)/g, '<audio\n        id="el-$1-voice"\n        data-audio-group="voiceover"');
  let lane = 0;
  html = html.replace(/<audio\s+id="el-[^"]+-voice"[^>]*>/g, (tag) =>
    tag
      .replace(/data-track-index="\d+"/, `data-track-index="${lane++ % 2 === 0 ? 10 : 12}"`)
      .replace(/\s*data-fx-chain="[^"]*"/, "")
      .replace(/(\s*)>$/, `\n        data-fx-chain="${attr(VOICE_CHAIN)}"$1>`),
  );
  html = html.replace(/<audio\s+id="el-sfx-(\d+)"\s+src="([^"]+)"\s+data-start="([\d.]+)"([^>]*)><\/audio>/g, (_tag, idx: string, src: string, start: string, rest: string) => {
    const cue = sound.sfx[Number(idx)];
    if (!cue) fail(`index.html: лишний звук el-sfx-${idx}`);
    cue.id = `sfx-${cue.kind}-${String(cue.frame).padStart(2, "0")}`;
    const dur = /data-duration="([\d.]+)"/.exec(rest)?.[1];
    const laneAttr = /data-track-index="(\d+)"/.exec(rest)?.[1];
    const vol = /data-volume="([\d.]+)"/.exec(rest)?.[1];
    return `<audio\n        id="${cue.id}"\n        src="${src}"\n        data-start="${r3(Number(start))}"\n        data-duration="${dur}"\n        data-track-index="${laneAttr}"\n        data-volume="${vol}"\n        data-audio-group="sfx"\n      ></audio>`;
  });
  html = html.replace(/data-start="(\d+\.\d{4,})"/g, (_m, v: string) => `data-start="${r3(Number(v))}"`);
  const buses = `
      <!-- mix buses (engine/src/assemble.ts) -->
      <hf-audio-group id="voiceover" data-label="Voice" data-volume="1"></hf-audio-group>
      <hf-audio-group id="music" data-label="Music" data-volume="1"></hf-audio-group>
      <hf-audio-group id="sfx" data-label="SFX" data-volume="1"></hf-audio-group>
      <audio
        id="music-drone"
        src="assets/music/drone.wav"
        data-start="0"
        data-duration="${sound.drone.cut}"
        data-track-index="11"
        data-volume="${sound.drone.volume}"
        data-audio-group="music"
      ></audio>`;
  const overlays =
    flashTr.map((_, i) => `\n      <div id="hf-flash-${i}" class="hf-flash" aria-hidden="true" data-layout-ignore></div>`).join("") +
    (flashTr.length ? `\n      <canvas id="hf-burst" width="540" height="960" aria-hidden="true" data-layout-ignore></canvas>` : "") +
    `
      <div id="hf-vignette" aria-hidden="true" data-layout-ignore></div>
      <div id="grain-overlay" aria-hidden="true" data-layout-ignore><div id="grain-texture"><div id="grain-dark"></div><div id="grain-light"></div></div></div>`;
  const beforeRootClose = /(\n\s*<\/div>\s*\n\s*<script>)/;
  if (!beforeRootClose.test(html)) fail("index.html: не найден конец корня перед скриптом");
  html = html.replace(beforeRootClose, (m) => `${buses}\n${overlays}${m}`);

  // 4. main timeline: HyperShader seam(s) + grain stepped by timeline time + full-span anchor
  const shaderScenes = [...new Set(shaderTr.flatMap((tr) => [`el-${tr.from}`, `el-${tr.to}`]))];
  const shaderTransitions = shaderTr.map((tr) => ({
    time: (timings.find((t) => t.id === tr.to) as BeatTiming).start,
    shader: tr.shader,
    duration: tr.duration,
    ease: tr.ease,
  }));
  const flashes = flashTr.map((tr) => ({ at: (timings.find((t) => t.id === tr.to) as BeatTiming).start, dur: tr.duration }));
  const ashColors = JSON.stringify([colors.ashMid, colors.ash3, colors.plane, colors.ashLight]);
  // CSS flash over a cut: bone overlay ramps in over the last 0.08 s of the outgoing scene (its settle frame stays clean), holds, fades out by `dur`;
  // an ash burst sprays from the hero line. One writer (the main driver), pure function of time.
  const flashJs = flashes.length
    ? `
        var FLASHES = ${JSON.stringify(flashes)};
        var flashEls = FLASHES.map(function (f, i) { return document.getElementById("hf-flash-" + i); });
        var bctx = document.getElementById("hf-burst").getContext("2d");
        var ASH_COLORS = ${ashColors};
        function prand(n) { var x = Math.sin(n * 127.1 + 311.7) * 43758.5453; return x - Math.floor(x); }
        var ASH = [];
        for (var i = 0; i < 180; i++) {
          ASH.push({ a: prand(i * 1.7 + 0.3) * 6.2832, v: 700 + 1500 * prand(i * 2.9 + 1.1), r: 2 + 8 * Math.pow(prand(i * 3.3 + 2.2), 1.6),
            c: ASH_COLORS[i % ASH_COLORS.length], life: 0.8 + 0.7 * prand(i * 4.1 + 0.7), lag: 0.06 * prand(i * 5.3 + 1.9) });
        }
        function flashAlpha(d, dur) {
          if (d <= -0.08 || d >= dur) return 0;
          if (d < 0) { var u = 1 + d / 0.08; return u * u; }
          if (d < 0.08) return 1;
          var p = (d - 0.08) / (dur - 0.08);
          return (1 - p) * (1 - p);
        }
        function drawFlashes(t) {
          bctx.setTransform(1, 0, 0, 1, 0, 0);
          bctx.clearRect(0, 0, 540, 960);
          bctx.setTransform(0.5, 0, 0, 0.5, 0, 0);
          for (var k = 0; k < FLASHES.length; k++) {
            var f = FLASHES[k], d = t - f.at;
            flashEls[k].style.opacity = flashAlpha(d, f.dur).toFixed(3);
            if (d < 0 || d > 1.6) continue;
            for (var j = 0; j < ASH.length; j++) {
              var q = ASH[j], age = d - q.lag;
              if (age <= 0 || age >= q.life) continue;
              var s = 0.3 * (1 - Math.exp(-age / 0.3));
              var x = 540 + Math.cos(q.a) * q.v * s;
              var y = 760 + Math.sin(q.a) * q.v * s * 0.8 + 140 * age * age;
              bctx.globalAlpha = 0.85 * (1 - age / q.life);
              bctx.fillStyle = q.c;
              bctx.beginPath(); bctx.arc(x, y, q.r * (1 + 0.8 * age), 0, 6.2832); bctx.fill();
            }
          }
          bctx.globalAlpha = 1;
        }`
    : "";
  const init = shaderTr.length
    ? `HyperShader.init({ bgColor: "${colors.ground}", accentColor: "${colors.accent}", compositionId: "main", scenes: ${JSON.stringify(shaderScenes)}, transitions: ${JSON.stringify(shaderTransitions)} })`
    : "gsap.timeline({ paused: true })";
  const mainScript = `<script>
      (function () {
        var TOTAL = ${total};
        var tl = ${init};
        var grain = document.getElementById("grain-texture");
        var OFFS = [[0, 0], [-5, -5], [-10, 5], [5, -10], [-5, 15], [-10, 5], [15, 0], [0, 10], [-15, 0], [10, 5], [3, -7], [-12, -3], [8, 12]];
${flashJs}
        var drive = { t: 0 };
        tl.fromTo(drive, { t: 0 }, {
          t: TOTAL,
          duration: TOTAL,
          ease: "none",
          onUpdate: function () {
            var o = OFFS[Math.floor(drive.t * 24) % OFFS.length];
            grain.style.transform = "translate(" + o[0] + "%, " + o[1] + "%)";${flashes.length ? "\n            drawFlashes(drive.t);" : ""}
          },
        }, 0);
        tl.to({}, { duration: TOTAL }, 0);
        window.__timelines = window.__timelines || {};
        window.__timelines["main"] = tl;
      })();
    </script>`;
  const scriptRe = /<script>\s*window\.__timelines = window\.__timelines \|\| \{\};\s*window\.__timelines\["main"\] = gsap\.timeline\(\{ paused: true \}\);\s*<\/script>/;
  if (!scriptRe.test(html)) fail("index.html: не найден скрипт главного таймлайна");
  html = html.replace(scriptRe, () => mainScript);
  writeFileSync(indexPath, html);
  log.info(`index.html: ${hosts.length} сцен, переходов: шейдер ${shaderTr.length}, вспышка ${flashTr.length}; звуков ${sound.sfx.length}, гул 0–${sound.drone.cut} с, всего ${total} с`);
  return total;
}

/** Voiceover carve (vendored hyperframes-audio/scripts/carve.mjs) for every bed that plays under speech. */
function carveBeds({ buildDir, timings, sound }: AssembleInput): void {
  const script = join(VENDOR_SKILLS, "hyperframes-audio", "scripts", "carve.mjs");
  const voicesOver = (a: number, b: number): string[] =>
    timings.filter((t) => t.start < b - 0.05 && t.end > a + 0.05).map((t) => `el-${t.id}-voice`);
  const beds: { id: string; start: number; end: number; strength: number }[] = [];
  if (sound.drone.carve) beds.push({ id: "music-drone", start: 0, end: sound.drone.cut, strength: sound.drone.carve });
  for (const c of sound.sfx) if (c.carve && c.id) beds.push({ id: c.id, start: c.at, end: c.at + c.duration_s, strength: c.carve });
  for (const bed of beds) {
    const voices = voicesOver(bed.start, bed.end);
    if (!voices.length) continue;
    run(process.execPath, [script, "--comp", "index.html", "--bed", bed.id, ...voices.flatMap((v) => ["--voice", v]), "--strength", String(bed.strength)], { cwd: buildDir });
    log.info(`приглушение ${bed.id} под голос (${voices.length}) · сила ${bed.strength}`);
  }
}

function writeVerifyPlan({ spec, buildDir, timings, scenes }: AssembleInput, style: StyleDef, total: number): void {
  const [width, height] = spec.format.split("x").map(Number);
  writeJson(join(buildDir, "verify_plan.json"), {
    id: spec.id,
    fps: spec.fps,
    width,
    height,
    duration: total,
    contentMaxY: style.safeZone.contentMaxY,
    loudness: { target: -14, tolerance: 0.5, maxTruePeak: -1.5 },
    scenes: timings.map((t, i) => {
      const sc = scenes[i] as SceneBuild;
      return {
        id: t.id,
        start: t.start,
        end: t.end,
        settle: r3(t.start + warpAt(sc.warp, sc.settle)),
        events: sc.events.map((ev) => ({ t: r3(t.start + warpAt(sc.warp, ev.ref)), label: ev.label })),
      };
    }),
  });
}
