import { readFileSync, writeFileSync } from "node:fs";
import type { StyleDef } from "./contract.ts";
import { substituteStyle, toneColors } from "./contract.ts";
import { join } from "node:path";
import type { SceneBuild } from "./scenes.ts";
import type { SoundPlan } from "./sound.ts";
import type { VideoSpec } from "./spec.ts";
import type { BeatTiming } from "./timeline.ts";
import { warpAt, wordTime } from "./timeline.ts";
import type { LookDef } from "./look.ts";
import { paletteCss } from "./look.ts";
import { backgroundHostsHtml, installRuntime, layerHostsHtml, motionConfig, planTransitions, postOverlays, prepareBackgrounds, vignetteCss, writeTextureLayers } from "./layers.ts";
import { installDevices } from "./devices.ts";
import type { VoiceLine } from "./voice.ts";
import type { BeatWords } from "./words.ts";
import { ENGINE_DIR, VENDOR_SKILLS, copyInto, ensureDir, fail, log, r3, run, stripAnsi, writeJson } from "./lib/util.ts";

export interface AssembleInput {
  spec: VideoSpec;
  style: StyleDef;
  look: LookDef;
  buildDir: string;
  voices: VoiceLine[];
  words: BeatWords[];
  timings: BeatTiming[];
  sound: SoundPlan;
  scenes: SceneBuild[];
}

// Voice chain rides on every narration clip, never on a bus: a bus with data-fx-chain fails on the
// engine's float WAV (TRAPS.md, «FX на аудиошине»).
const VOICE_CHAIN = {
  version: 1,
  nodes: [
    { type: "highpass", id: "n1", label: "Remove Rumble", params: { frequency: 70, q: 0.707, poles: "2" } },
    { type: "peaking", id: "n2", label: "Reduce Mud", params: { frequency: 250, gain: -2, q: 1.2 } },
    { type: "peaking", id: "n4", label: "Add Clarity", params: { frequency: 3000, gain: 1.5, q: 1 } },
    { type: "limiter", id: "n5", label: "Peak Ceiling", params: { limit: -2.5, attack: 5, release: 60, level_out: 0 } },
  ],
};

const attr = (o: unknown): string => JSON.stringify(o).replace(/&/g, "&amp;").replace(/"/g, "&quot;");

function nodeScript(script: string, args: string[], cwd: string, keep = 8): void {
  const r = run(process.execPath, [script, ...args], { cwd });
  const lines = stripAnsi(r.stdout + r.stderr).trim().split("\n").filter((l) => l.trim());
  for (const line of lines.slice(0, keep)) log.info(line.trim());
}

/**
 * HyperFrames project in build/: captions.mjs → assemble-index.mjs (vendored skill scripts) →
 * finishing pass (buses, drone, SFX, shader transition, grain, vignette, local scripts) → carve.
 */
export function assembleProject(input: AssembleInput): number {
  const { spec, style, buildDir } = input;
  stage(spec, style, buildDir);
  writeStoryboard(input);
  writeAudioMeta(input);
  const scripts = join(VENDOR_SKILLS, "faceless-explainer", "scripts");
  nodeScript(join(scripts, "captions.mjs"), ["build", "--storyboard", "STORYBOARD.md", "--audio-meta", "audio_meta.json", "--hyperframes", ".", "--out", "caption_groups.json"], buildDir, 3);
  nodeScript(join(scripts, "assemble-index.mjs"), ["--storyboard", "STORYBOARD.md", "--hyperframes", "."], buildDir, 12);
  const total = finalizeIndex(input, style);
  carveBeds(input);
  writeVerifyPlan(input, style, total);
  return total;
}

function stage(spec: VideoSpec, style: StyleDef, buildDir: string): void {
  copyInto(join(ENGINE_DIR, "assets", "fonts"), join(buildDir, "assets", "fonts"));
  copyInto(join(ENGINE_DIR, "assets", "vendor"), join(buildDir, "assets", "vendor"));
  copyInto(join(ENGINE_DIR, "styles", spec.style, "frame.md"), join(buildDir, "frame.md"));
  const skin = readFileSync(join(ENGINE_DIR, "captions", `${spec.captions}.html`), "utf8");
  ensureDir(join(buildDir, ".hyperframes"));
  writeFileSync(join(buildDir, ".hyperframes", "caption-skin.html"), substituteStyle(skin, style, "accent", `engine/captions/${spec.captions}.html`));
  writeJson(join(buildDir, "hyperframes.json"), {
    $schema: "https://hyperframes.heygen.com/schema/hyperframes.json",
    paths: { blocks: "compositions", components: "compositions/components", assets: "assets" },
    media: { autoProxy: true },
  });
  writeJson(join(buildDir, "meta.json"), { id: spec.id, name: spec.id });
}

function writeStoryboard({ spec, buildDir, timings, voices }: AssembleInput): void {
  const total = (timings[timings.length - 1] as BeatTiming).end;
  const lines = [
    "---",
    `format: ${spec.format}`,
    `duration: ${total}s`,
    `message: ${JSON.stringify(spec.title)}`,
    "arc: story-explainer",
    "mode: autonomous",
    "---",
    "",
    `# STORYBOARD — ${spec.id}`,
    "",
    "> Generated by the hygen engine from video.json on every build. Do not edit.",
    "",
  ];
  spec.beats.forEach((beat, i) => {
    const t = timings[i] as BeatTiming;
    lines.push(
      `## Frame ${i + 1} — ${beat.id}`,
      `- duration: ${t.duration}s`,
      "- status: animated",
      `- src: compositions/frames/${beat.id}.html`,
      `- transition_in: ${spec.transitions.find((tr) => tr.to === beat.id && tr.type === "shader")?.shader ?? "cut"}`,
      `- voiceover: ${JSON.stringify((voices[i] as VoiceLine).tts)}`,
      "",
    );
  });
  writeFileSync(join(buildDir, "STORYBOARD.md"), lines.join("\n"));
}

function writeAudioMeta({ buildDir, voices, words, sound }: AssembleInput): void {
  writeJson(join(buildDir, "audio_meta.json"), {
    bgm: null,
    bgm_pending: false,
    voices: voices.map((v, i) => ({ frame: i + 1, path: v.rel, duration_s: v.duration, words: (words[i] as BeatWords).tokens })),
    sfx: sound.sfx.map((c) => ({ frame: c.frame, file: c.file, offset_s: c.offset_s, duration_s: c.duration_s, volume: c.volume })),
  });
}

/** Finishing pass over assemble-index's output — ported from examples/pompeii-short/scripts/assemble/finalize_index.mjs. */
function finalizeIndex({ spec, look, buildDir, timings, words, sound, scenes }: AssembleInput, style: StyleDef): number {
  const colors = toneColors(style, "accent");
  const indexPath = join(buildDir, "index.html");
  let html = readFileSync(indexPath, "utf8");

  const hosts: { id: string; block: string }[] = [];
  for (const m of html.matchAll(/<div\s+id="el-([^"]+)"\s+class="scene"([^>]*)><\/div>/g)) {
    if (/data-composition-src="compositions\/frames\//.test(m[2] as string)) hosts.push({ id: m[1] as string, block: m[0] });
  }
  if (hosts.length !== timings.length) fail(`index.html: ожидалось ${timings.length} сцен, найдено ${hosts.length}`);
  const total = Number(/data-composition-id="main"[^>]*?data-duration="([\d.]+)"/s.exec(html)?.[1]);
  if (!Number.isFinite(total)) fail("index.html: нет data-duration у корня");

  // 1. hosts: the outgoing scene of a shader transition is held under the blend; solid grounds for the shader pair
  const shaderTr = spec.transitions.filter((tr) => tr.type === "shader");
  // look layers: transitions over the cuts (video.json, beat, look hit/default), media backgrounds, textures, motion runtime
  const hits = sound.sfx.filter((c) => c.kind !== "ash-fall").map((c) => c.at);
  const heavy = sound.sfx.filter((c) => c.kind === "thud-heavy").map((c) => c.at);
  const planned = planTransitions(spec, look, timings, heavy);
  const flashTr = planned.filter((tr) => tr.list.includes("flash"));
  const burstTr = planned.filter((tr) => tr.list.includes("ash-burst"));
  const spans = spec.beats.map((beat, i) => ({ beat, timing: timings[i] as BeatTiming, index: i }));
  const bgs = prepareBackgrounds({ beats: spans.map(({ beat, timing }) => ({ beat, start: timing.start, duration: timing.duration })), look, style, videoDir: join(buildDir, ".."), dir: buildDir, fps: spec.fps });
  const layers = writeTextureLayers({
    look,
    style,
    dir: buildDir,
    total,
    hits,
    spans: spans.map(({ beat, timing, index }) => ({ beatId: beat.id, start: timing.start, duration: timing.duration, textures: beat.textures, word: (ref: string) => wordTime(words[index] as BeatWords, ref) })),
  });
  const motion = motionConfig({ id: spec.id, look, style, beats: spans.map(({ beat, timing, index }) => ({ beat, start: timing.start, end: timing.end, index })), hits, bgs, layers, transitions: planned });
  const runtime = motion.needs.runtime || scenes.some((s) => s.injected);
  if (runtime) installRuntime(buildDir);
  const stageBeats = spec.beats.some((b) => b.scene === undefined);
  if (stageBeats) installDevices(buildDir);
  const post = postOverlays(motion.needs);
  writeJson(join(buildDir, "layers.json"), { look: look.id, textures: layers, backgrounds: bgs, transitions: planned, motion: motion.config });
  const held = new Map<string, number>();
  for (const tr of shaderTr) {
    const from = timings.find((t) => t.id === tr.from) as BeatTiming;
    held.set(tr.from, r3(from.duration + tr.duration));
  }
  const shaderIds = new Set(shaderTr.flatMap((tr) => [tr.from, tr.to]));
  hosts.forEach((h, i) => {
    let block = h.block.replace(/\sstyle="[^"]*"/, "").replace(/data-track-index="\d+"/, `data-track-index="${i % 2}"`);
    const heldDur = held.get(h.id);
    if (heldDur) block = block.replace(/data-duration="[\d.]+"/, `data-duration="${heldDur}"`);
    if (shaderIds.has(h.id)) block = block.replace(/class="scene"/, `class="scene" style="background-color: ${colors.ground}"`);
    html = html.replace(h.block, block);
  });
  for (const [id, heldDur] of held) {
    const base = (timings.find((t) => t.id === id) as BeatTiming).duration;
    const framePath = join(buildDir, "compositions", "frames", `${id}.html`);
    let rootDone = false;
    const out = readFileSync(framePath, "utf8").replace(/<([A-Za-z][\w:-]*)\b([^>]*)>/g, (tag: string, name: string, attrs: string) => {
      const dm = /\bdata-duration="([\d.]+)"/.exec(attrs);
      if (!rootDone && attrs.includes(`data-composition-id="${id}"`)) {
        rootDone = true;
        return dm ? tag.replace(/\bdata-duration="[\d.]+"/, `data-duration="${heldDur}"`) : tag.replace(/(\s*\/?>)$/, ` data-duration="${heldDur}"$1`);
      }
      if (!dm || name.toLowerCase() === "audio") return tag;
      const sm = /\bdata-start="([\d.]+)"/.exec(attrs);
      if (!sm) return tag;
      const start = Number(sm[1]);
      if (start + Number(dm[1]) < base - 0.011) return tag;
      return tag.replace(/\bdata-duration="[\d.]+"/, `data-duration="${r3(heldDur - start)}"`);
    });
    if (!rootDone) fail(`${framePath}: нет корня data-composition-id="${id}"`);
    writeFileSync(framePath, out);
  }

  // 2. head: GSAP and the shader runtime from the project, never a CDN; overlay styles
  html = html.replace(/<script src="https:\/\/cdn\.jsdelivr\.net\/npm\/gsap@[^"]+"[^>]*><\/script>/, () =>
    '<script src="assets/vendor/gsap.min.js"></script>' +
    (shaderTr.length ? '\n    <script src="assets/vendor/shader-transitions.global.js"></script>' : "") +
    (runtime ? '\n    <script src="assets/hygen/runtime.js"></script>' : "") +
    (stageBeats ? '\n    <script src="assets/hygen/devices.js"></script>' : ""),
  );
  if (/https?:\/\/cdn\./.test(html)) fail("index.html: остались скрипты с CDN");
  const overlayCss = `
      /* global finish (engine/src/assemble.ts): palette of the look as CSS variables, vignette, transition overlays */
      ${paletteCss(style)}
      #el-captions { z-index: 35; }
      ${vignetteCss(style)}` +
    (flashTr.length
      ? `
      .hf-flash { position: absolute; inset: 0; pointer-events: none; z-index: 28; background-color: ${colors.text}; opacity: 0; }`
      : "") +
    (burstTr.length
      ? `
      #hf-burst { position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; pointer-events: none; z-index: 29; }`
      : "") +
    (post.css ? `\n      ${post.css}` : "");
  html = html.replace(/(\s*)<\/style>\s*<\/head>/, () => `${overlayCss}\n    </style>\n  </head>`);

  // 3. body: voices on the voiceover bus (lanes 10/12 — lint duplicate_audio_track), SFX ids + bus, rounding
  html = html.replace(/<audio\s+id="el-([^"]+)-voice"(?![^>]*data-audio-group)/g, '<audio\n        id="el-$1-voice"\n        data-audio-group="voiceover"');
  let lane = 0;
  html = html.replace(/<audio\s+id="el-[^"]+-voice"[^>]*>/g, (tag) =>
    tag
      .replace(/data-track-index="\d+"/, `data-track-index="${lane++ % 2 === 0 ? 10 : 12}"`)
      .replace(/\s*data-fx-chain="[^"]*"/, "")
      .replace(/(\s*)>$/, `\n        data-fx-chain="${attr(VOICE_CHAIN)}"$1>`),
  );
  html = html.replace(/<audio\s+id="el-sfx-(\d+)"\s+src="([^"]+)"\s+data-start="([\d.]+)"([^>]*)><\/audio>/g, (_tag, idx: string, src: string, start: string, rest: string) => {
    const cue = sound.sfx[Number(idx)];
    if (!cue) fail(`index.html: лишний звук el-sfx-${idx}`);
    cue.id = `sfx-${cue.kind}-${String(cue.frame).padStart(2, "0")}`;
    const dur = /data-duration="([\d.]+)"/.exec(rest)?.[1];
    const laneAttr = /data-track-index="(\d+)"/.exec(rest)?.[1];
    const vol = /data-volume="([\d.]+)"/.exec(rest)?.[1];
    return `<audio\n        id="${cue.id}"\n        src="${src}"\n        data-start="${r3(Number(start))}"\n        data-duration="${dur}"\n        data-track-index="${laneAttr}"\n        data-volume="${vol}"\n        data-audio-group="sfx"\n      ></audio>`;
  });
  html = html.replace(/data-start="(\d+\.\d{4,})"/g, (_m, v: string) => `data-start="${r3(Number(v))}"`);
  const buses = `
      <!-- mix buses (engine/src/assemble.ts) -->
      <hf-audio-group id="voiceover" data-label="Voice" data-volume="1"></hf-audio-group>
      <hf-audio-group id="music" data-label="Music" data-volume="1"></hf-audio-group>
      <hf-audio-group id="sfx" data-label="SFX" data-volume="1"></hf-audio-group>
      <audio
        id="music-drone"
        src="assets/music/drone.wav"
        data-start="0"
        data-duration="${sound.drone.cut}"
        data-track-index="11"
        data-volume="${sound.drone.volume}"
        data-audio-group="music"
      ></audio>`;
  const overlays =
    backgroundHostsHtml(bgs) +
    flashTr.map((_, i) => `\n      <div id="hf-flash-${i}" class="hf-flash" aria-hidden="true" data-layout-ignore></div>`).join("") +
    (burstTr.length ? `\n      <canvas id="hf-burst" width="540" height="960" aria-hidden="true" data-layout-ignore></canvas>` : "") +
    `
      <div id="hf-vignette" aria-hidden="true" data-layout-ignore></div>` +
    post.html +
    layerHostsHtml(layers);
  const beforeRootClose = /(\n\s*<\/div>\s*\n\s*<script>)/;
  if (!beforeRootClose.test(html)) fail("index.html: не найден конец корня перед скриптом");
  html = html.replace(beforeRootClose, (m) => `${buses}\n${overlays}${m}`);

  // 4. main timeline: HyperShader seam(s) + grain stepped by timeline time + full-span anchor
  const shaderScenes = [...new Set(shaderTr.flatMap((tr) => [`el-${tr.from}`, `el-${tr.to}`]))];
  const shaderTransitions = shaderTr.map((tr) => ({
    time: (timings.find((t) => t.id === tr.to) as BeatTiming).start,
    shader: tr.shader,
    duration: tr.duration,
    ease: tr.ease,
  }));
  const init = shaderTr.length
    ? `HyperShader.init({ bgColor: "${colors.ground}", accentColor: "${colors.accent}", compositionId: "main", scenes: ${JSON.stringify(shaderScenes)}, transitions: ${JSON.stringify(shaderTransitions)} })`
    : "gsap.timeline({ paused: true })";
  const mainScript = `<script>
      (function () {
        var TOTAL = ${total};
        var tl = ${init};
${runtime ? `        HygenMotion.root.init(${JSON.stringify(motion.config)});` : ""}
        var drive = { t: 0 };
        tl.fromTo(drive, { t: 0 }, {
          t: TOTAL,
          duration: TOTAL,
          ease: "none",
          onUpdate: function () {${runtime ? "\n            HygenMotion.root.update(drive.t);" : ""}
          },
        }, 0);
        tl.to({}, { duration: TOTAL }, 0);
        window.__timelines = window.__timelines || {};
        window.__timelines["main"] = tl;
      })();
    </script>`;
  const scriptRe = /<script>\s*window\.__timelines = window\.__timelines \|\| \{\};\s*window\.__timelines\["main"\] = gsap\.timeline\(\{ paused: true \}\);\s*<\/script>/;
  if (!scriptRe.test(html)) fail("index.html: не найден скрипт главного таймлайна");
  html = html.replace(scriptRe, () => mainScript);
  writeFileSync(indexPath, html);
  log.info(`index.html: ${hosts.length} сцен, переходов: шейдер ${shaderTr.length}, вспышка ${flashTr.length}, пепел ${burstTr.length}, всего переходов ${planned.length}; look ${look.id}, текстур ${layers.length}, фонов ${bgs.length}${runtime ? ", runtime motion" : ""}; звуков ${sound.sfx.length}, гул 0–${sound.drone.cut} с, всего ${total} с`);
  return total;
}

/** Voiceover carve (vendored hyperframes-audio/scripts/carve.mjs) for every bed that plays under speech. */
function carveBeds({ buildDir, timings, sound }: AssembleInput): void {
  const script = join(VENDOR_SKILLS, "hyperframes-audio", "scripts", "carve.mjs");
  const voicesOver = (a: number, b: number): string[] =>
    timings.filter((t) => t.start < b - 0.05 && t.end > a + 0.05).map((t) => `el-${t.id}-voice`);
  const beds: { id: string; start: number; end: number; strength: number }[] = [];
  if (sound.drone.carve) beds.push({ id: "music-drone", start: 0, end: sound.drone.cut, strength: sound.drone.carve });
  for (const c of sound.sfx) if (c.carve && c.id) beds.push({ id: c.id, start: c.at, end: c.at + c.duration_s, strength: c.carve });
  for (const bed of beds) {
    const voices = voicesOver(bed.start, bed.end);
    if (!voices.length) continue;
    run(process.execPath, [script, "--comp", "index.html", "--bed", bed.id, ...voices.flatMap((v) => ["--voice", v]), "--strength", String(bed.strength)], { cwd: buildDir });
    log.info(`приглушение ${bed.id} под голос (${voices.length}) · сила ${bed.strength}`);
  }
}

function writeVerifyPlan({ spec, buildDir, timings, scenes }: AssembleInput, style: StyleDef, total: number): void {
  const [width, height] = spec.format.split("x").map(Number);
  writeJson(join(buildDir, "verify_plan.json"), {
    id: spec.id,
    fps: spec.fps,
    width,
    height,
    duration: total,
    contentMaxY: style.safeZone.contentMaxY,
    loudness: { target: -14, tolerance: 0.5, maxTruePeak: -1.5 },
    scenes: timings.map((t, i) => {
      const sc = scenes[i] as SceneBuild;
      return {
        id: t.id,
        start: t.start,
        end: t.end,
        settle: r3(t.start + warpAt(sc.warp, sc.settle)),
        events: sc.events.map((ev) => ({ t: r3(t.start + warpAt(sc.warp, ev.ref)), label: ev.label })),
      };
    }),
  });
}
